declare module 'cors';
declare module 'bcrypt';
declare module 'express-fileupload';
declare module 'jsonwebtoken';
declare module 'swagger-jsdoc';
declare module 'swagger-ui-express';
declare module 'morgan';
declare module 'nodemailer';
declare module 'cookie-parser';